# ----------------------------------------------------------------------------#
#                                                                             #
#                      Rock Paper Scissors config                             #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
#   the default.yml file is overwritten on every server restart!
#   This means you will have to use the other files to customize the messages, but since i am adding messages regulary in updates
#   you can use the default file if you just want to have the up to date english default messages
langFile: "default"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "shears"
    # display name of the button
    displayName: "&3Rock Paper Scissors"
    # lore of the button
    lore:
    - ""
    - "&1Fight like real men"
  gameButtons:
    saveStats:
      materialData: "PAPER"
      displayName: "&l&1Rock Paper Scissors"
      lore:
      - ""
      - '&1Cost: &45'
      - '&1Reward: &29'
      - ""
      - "&1Best of five rounds"
      # slot of the button in the gui
      #   be careful to not use the same twice ;)
      slot: 22
      cost: 5
      reward: 9
      # time in seconds for each turn (default 10)
      timePerTurn: 10
      # time in seconds between turns (default 5)
      waitPerTurn: 5
      inviteGuiTitle: "     &3Rock Paper Scissors"
      saveStats: true
      # Only use numbers up to 9. Preferably uneven ones to get rid of draws.
      rounds: 5
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "nether_star"
      displayName: "&l&cTop list"
      lore:
      - ""
      - "&1Rock Paper Scissors scores"
      slot: 31
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '              Top List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %wins% for the number of wins
      skullLore:
      - ''
      - '&6Rank:&1 %rank%'
      - '&6Wins:&1 %wins%'

scissors:
  materialData: 'shears'
  displayName: '&5Scissors'
paper:
  materialData: 'paper'
  displayName: '&5Paper'
rock:
  materialData: 'cobblestone'
  displayName: '&5Rock'

# indicators
indicatorWon:
  materialData: 'LIME_STAINED_GLASS_PANE'
  displayName: '&5Won'
indicatorPlaceholder:
  materialData: 'GRAY_STAINED_GLASS_PANE'
  displayName: '&5'
